### ISSUE TITLE
`pthread_create` symbol not found when statically linking glibc.

### ISSUE THREAD

**Issue by gaoqiangz** [EmbarkStudios/crash-handling#98]
.cargo/config.toml

```toml
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
```

`ptr` will be null

https://github.com/EmbarkStudios/crash-handling/blob/0744245fbf8cb1b46252f427fadae54826f091c2/crash-handler/src/unix/pthread_interpose.rs#L72-L73
